// Writes <link rel="modulepreload"> for every module app.js imports at start-up into k7/index.html, so the browser fetches
// them all at once instead of discovering them one import level at a time.   node .github/scripts/preload.mjs [--check]
import fs from "node:fs"; import path from "node:path";
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "../../k7"), html = path.join(root, "index.html");
const seen = new Set(), urls = [];
const walk = f => { for (const m of fs.readFileSync(f, "utf8").matchAll(/^\s*import\s+(?:[^"';]*?from\s+)?["']([^"']+)["']/gm)) {
  if (/^https?:/.test(m[1])) continue;
  const abs = path.resolve(path.dirname(f), m[1].replace(/\?.*$/, "")), url = path.relative(root, abs) + (m[1].includes("?") ? m[1].slice(m[1].indexOf("?")) : "");
  if (seen.has(url)) continue; seen.add(url); urls.push(url); walk(abs); } };
walk(path.join(root, "js/app.js"));
const block = `<!-- modulepreload:start (generated by .github/scripts/preload.mjs) -->\n${urls.map(u => `<link rel="modulepreload" href="${u}">`).join("\n")}\n<!-- modulepreload:end -->`;
const src = fs.readFileSync(html, "utf8"), re = /<!-- modulepreload:start[\s\S]*?modulepreload:end -->/;
const out = re.test(src) ? src.replace(re, block) : src.replace("</head>", `${block}\n</head>`);
if (process.argv.includes("--check")) { if (out !== src) { console.error("k7/index.html modulepreload list is out of date: run node .github/scripts/preload.mjs"); process.exit(1); } console.log(`modulepreload ok (${urls.length})`); }
else { fs.writeFileSync(html, out); console.log(`modulepreload: ${urls.length} modules`); }
