// Staff-facing Arabic names. English stays the stock name.
export const AR = {
  "bib-coke": "شراب كولا",
  "bib-coke-zero": "شراب كولا زيرو",
  "bib-fanta": "شراب فانتا",
  "lemonade-syrup": "شراب ليموناضة",
  "mojito-syrup": "شراب موهيتو",
  "bib-sprite": "شراب سبرايت",
  "arwa-500": "مياه أروى ٥٠٠ مل",
  "arwa-zero": "أروى زيرو ٥٠٠ مل",
  "barbican": "باربيكان",
  "monster": "مونستر",
  "rani": "راني",
  "schweppes": "شويبس",
  "vimto-can": "فيمتو علبة ٢٥٠ مل",
  "vimto-pet": "فيمتو ٢٥٠ مل",
  "vimto-blueberry": "فيمتو توت ٢٥٠ مل",
  "mm-choco-150": "إم آند إمز شوكولاتة ١٥٠ غ",
  "mm-choco-45": "إم آند إمز شوكولاتة ٤٥ غ",
  "mm-peanut-150": "إم آند إمز فول سوداني ١٥٠ غ",
  "mm-peanut-45": "إم آند إمز فول سوداني ٤٥ غ",
  "maltesers-175": "مالتزرز ١٧٥ غ",
  "maltesers-37": "مالتزرز ٣٧ غ",
  "flossine-blue": "سكر غزل أزرق",
  "corn-butterfly": "ذرة فراشة",
  "caramel": "كراميل",
  "cheese-masala": "جبن ماسالا",
  "cotton-candy-tub": "علبة غزل البنات",
  "corn-mushroom": "ذرة مشروم",
  "pizza-mix": "خلطة بيتزا",
  "popcorn-oil": "زيت الفشار",
  "tub-130": "علبة فشار ١٣٠ أونصة",
  "tub-46": "علبة فشار ٤٦ أونصة",
  "tub-64": "علبة فشار ٦٤ أونصة",
  "tub-85": "علبة فشار ٨٥ أونصة",
  "salt": "ملح",
  "sugar": "سكر",
  "flossine-pink": "سكر غزل وردي",
  "hotdog": "هوت دوغ",
  "cheese-sauce": "صوص جبن",
  "hotdog-bun": "خبز هوت دوغ",
  "jalapeno": "هالابينو",
  "mustard": "صوص مستردة",
  "salsa": "صلصة ناتشوز",
  "nachos-chips": "رقائق ناتشوز",
  "ketchup": "كاتشب",
  "slush-blue": "سلش توت أزرق",
  "slush-glass-12": "كوب سلش ١٢ أونصة",
  "slush-glass-16": "كوب سلش ١٦ أونصة",
  "slush-pom": "سلش رمان",
  "slush-straw": "سلش فراولة",
  "brown-sugar": "سكر بني",
  "coffee-cup-big": "كوب قهوة كبير مع غطاء",
  "coffee-cup-small": "كوب قهوة صغير مع غطاء",
  "lemon": "ليمون",
  "mint": "نعناع",
  "sugar-sachet": "ظرف سكر",
  "sweet-low": "سويت أند لو",
  "cups-16": "كوب مشروب ١٦ أونصة",
  "cups-24": "كوب مشروب ٢٤ أونصة",
  "cups-30": "كوب مشروب ٣٠ أونصة",
  "dip-cup-4": "كوب صوص ٤ أونصة",
  "hotdog-tray": "صحن هوت دوغ",
  "lids-16": "غطاء كوب ١٦ أونصة",
  "lids-24": "غطاء كوب ٢٤ أونصة",
  "lids-30": "غطاء كوب ٣٠ أونصة",
  "nachos-tray-3": "صحن ناتشوز ٣ عيون",
  "nachos-tray-4": "صحن ناتشوز ٤ عيون",
  "napkin": "مناديل",
  "stirrer": "عصا تحريك",
  "straw": "شفاط",
  "straw-spoon": "شفاط بملعقة",
  "co2": "غاز ثاني أكسيد الكربون"
};
export const LOC_AR = { mini: "ميني ستور", refuel: "كونسيشن", stores: "المستودع الرئيسي" };
